name: OTA Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./Aways+_new

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create Update Zip
        run: |
          cd dist
          zip -r ../../update.zip .
          cd ../..

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: update.zip
          prerelease: false
